In [1]:
""" Auto Tagging Support Tickets Using LLM
Objective:
Automatically tag support tickets into categories using a large language model (LLM).
Dataset:
Free-text Support Ticket Dataset  Instructions:
●	Use prompt engineering or fine-tuning with an LLM ● Compare zero-shot vs fine-tuned performance
●	Apply few-shot learning techniques to improve accuracy
●	Output top 3 most probable tags per ticket
Skills Gained:
●	Prompt engineering
●	LLM-based text classification
●	Zero-shot and few-shot learning
●	Multi-class prediction and ranking
"""

' Auto Tagging Support Tickets Using LLM\nObjective:\nAutomatically tag support tickets into categories using a large language model (LLM).\nDataset:\nFree-text Support Ticket Dataset  Instructions:\n●\tUse prompt engineering or fine-tuning with an LLM ● Compare zero-shot vs fine-tuned performance\n●\tApply few-shot learning techniques to improve accuracy\n●\tOutput top 3 most probable tags per ticket\nSkills Gained:\n●\tPrompt engineering\n●\tLLM-based text classification\n●\tZero-shot and few-shot learning\n●\tMulti-class prediction and ranking\n'

In [2]:
!pip install transformers torch accelerate pandas -q

In [3]:
!pip install transformers torch accelerate pandas -q

In [4]:
from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [5]:
labels = [
    "Billing",
    "Technical Issue",
    "Account Access",
    "Refund",
    "Feature Request",
    "Complaint",
    "Shipping",
    "Product Inquiry"
]

In [6]:
ticket = "I paid for premium subscription but still cannot access premium features."

result = classifier(
    ticket,
    candidate_labels=labels,
    multi_label=True
)

top3 = list(zip(result["labels"][:3], result["scores"][:3]))

for tag, score in top3:
    print(tag, round(score,4))

Complaint 0.8006
Shipping 0.7391
Billing 0.739

In [7]:
import pandas as pd

df = pd.read_csv("customer_support_tickets.csv")

print(df.columns)
print("\n")
print(df.head())

Index(['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age',
       'Customer Gender', 'Product Purchased', 'Date of Purchase',
       'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status',
       'Resolution', 'Ticket Priority', 'Ticket Channel',
       'First Response Time', 'Time to Resolution',
       'Customer Satisfaction Rating'],
      dtype='object')


   Ticket ID        Customer Name              Customer Email  Customer Age  \
0          1        Marisa Obrien  carrollallison@example.com            32
1          2         Jessica Rios    clarkeashley@example.com            42
2          3  Christopher Robbins   gonzalestracy@example.com            48
3          4     Christina Dillon    bradleyolson@example.org            27
4          5    Alexander Carroll     bradleymark@example.com            67

  Customer Gender Product Purchased Date of Purchase      Ticket Type  \
0           Other        GoPro Hero       2021-03-22  Technical issue
1          Female       LG Smart TV       2021-05-22  Technical issue
2           Other          Dell XPS       2020-07-14  Technical issue
3          Female  Microsoft Office       2020-11-13  Billing inquiry
4          Female  Autodesk AutoCAD       2020-02-04  Billing inquiry

             Ticket Subject  \
0             Product setup
1  Peripheral compatibility
2           Network problem
3            Account access
4                 Data loss

                                  Ticket Description  \
0  I'm having an issue with the {product_purchase...
1  I'm having an issue with the {product_purchase...
2  I'm facing a problem with my {product_purchase...
3  I'm having an issue with the {product_purchase...
4  I'm having an issue with the {product_purchase...

               Ticket Status                                     Resolution  \
0  Pending Customer Response                                            NaN
1  Pending Customer Response                                            NaN
2                     Closed   Case maybe show recently my computer follow.
3                     Closed  Try capital clearly never color toward story.
4                     Closed                    West decision evidence bit.

  Ticket Priority Ticket Channel  First Response Time   Time to Resolution  \
0        Critical   Social media  2023-06-01 12:15:36                  NaN
1        Critical           Chat  2023-06-01 16:45:38                  NaN
2             Low   Social media  2023-06-01 11:14:38  2023-06-01 18:05:38
3             Low   Social media  2023-06-01 07:29:40  2023-06-01 01:57:40
4             Low          Email  2023-06-01 00:12:42  2023-06-01 19:53:42

   Customer Satisfaction Rating
0                           NaN
1                           NaN
2                           3.0
3                           3.0
4                           1.0

In [9]:
def get_top3_tags(text):
    result = classifier(
        text,
        candidate_labels=labels,
        multi_label=True
    )

    return list(zip(result["labels"][:3], result["scores"][:3]))

In [10]:
df_small = df.head(100).copy()

In [11]:
print(df_small.shape)
print(df_small.head())

(100, 17)
   Ticket ID        Customer Name              Customer Email  Customer Age  \
0          1        Marisa Obrien  carrollallison@example.com            32
1          2         Jessica Rios    clarkeashley@example.com            42
2          3  Christopher Robbins   gonzalestracy@example.com            48
3          4     Christina Dillon    bradleyolson@example.org            27
4          5    Alexander Carroll     bradleymark@example.com            67

  Customer Gender Product Purchased Date of Purchase      Ticket Type  \
0           Other        GoPro Hero       2021-03-22  Technical issue
1          Female       LG Smart TV       2021-05-22  Technical issue
2           Other          Dell XPS       2020-07-14  Technical issue
3          Female  Microsoft Office       2020-11-13  Billing inquiry
4          Female  Autodesk AutoCAD       2020-02-04  Billing inquiry

             Ticket Subject  \
0             Product setup
1  Peripheral compatibility
2           Network problem
3            Account access
4                 Data loss

                                  Ticket Description  \
0  I'm having an issue with the {product_purchase...
1  I'm having an issue with the {product_purchase...
2  I'm facing a problem with my {product_purchase...
3  I'm having an issue with the {product_purchase...
4  I'm having an issue with the {product_purchase...

               Ticket Status                                     Resolution  \
0  Pending Customer Response                                            NaN
1  Pending Customer Response                                            NaN
2                     Closed   Case maybe show recently my computer follow.
3                     Closed  Try capital clearly never color toward story.
4                     Closed                    West decision evidence bit.

  Ticket Priority Ticket Channel  First Response Time   Time to Resolution  \
0        Critical   Social media  2023-06-01 12:15:36                  NaN
1        Critical           Chat  2023-06-01 16:45:38                  NaN
2             Low   Social media  2023-06-01 11:14:38  2023-06-01 18:05:38
3             Low   Social media  2023-06-01 07:29:40  2023-06-01 01:57:40
4             Low          Email  2023-06-01 00:12:42  2023-06-01 19:53:42

   Customer Satisfaction Rating
0                           NaN
1                           NaN
2                           3.0
3                           3.0
4                           1.0

In [12]:
results = []

for i, text in enumerate(df_small["Ticket Description"]):
    print(f"Processing {i+1}/{len(df_small)}")

    result = classifier(
        text,
        candidate_labels=labels,
        multi_label=True
    )

    results.append(list(zip(result["labels"][:3], result["scores"][:3])))

df_small["Top3_Predicted_Tags"] = results

Processing 1/100
Processing 2/100
Processing 3/100
Processing 4/100
Processing 5/100
Processing 6/100
Processing 7/100
Processing 8/100
Processing 9/100

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Processing 10/100
Processing 11/100
Processing 12/100
Processing 13/100
Processing 14/100
Processing 15/100
Processing 16/100
Processing 17/100
Processing 18/100
Processing 19/100
Processing 20/100
Processing 21/100
Processing 22/100
Processing 23/100
Processing 24/100
Processing 25/100
Processing 26/100
Processing 27/100
Processing 28/100
Processing 29/100
Processing 30/100
Processing 31/100
Processing 32/100
Processing 33/100
Processing 34/100
Processing 35/100
Processing 36/100
Processing 37/100
Processing 38/100
Processing 39/100
Processing 40/100
Processing 41/100
Processing 42/100
Processing 43/100
Processing 44/100
Processing 45/100
Processing 46/100
Processing 47/100
Processing 48/100
Processing 49/100
Processing 50/100
Processing 51/100
Processing 52/100
Processing 53/100
Processing 54/100
Processing 55/100
Processing 56/100
Processing 57/100
Processing 58/100
Processing 59/100
Processing 60/100
Processing 61/100
Processing 62/100
Processing 63/100
Processing 64/100
Processing 65/100
Processing 66/100
Processing 67/100
Processing 68/100
Processing 69/100
Processing 70/100
Processing 71/100
Processing 72/100
Processing 73/100
Processing 74/100
Processing 75/100
Processing 76/100
Processing 77/100
Processing 78/100
Processing 79/100
Processing 80/100
Processing 81/100
Processing 82/100
Processing 83/100
Processing 84/100
Processing 85/100
Processing 86/100
Processing 87/100
Processing 88/100
Processing 89/100
Processing 90/100
Processing 91/100
Processing 92/100
Processing 93/100
Processing 94/100
Processing 95/100
Processing 96/100
Processing 97/100
Processing 98/100
Processing 99/100
Processing 100/100

In [13]:
df_small.to_csv("ticket_tagged_sample_100.csv", index=False)
print("Done!")

Done!

In [14]:
def format_tags(tag_list):
    return " | ".join([f"{t[0]} ({round(t[1],2)})" for t in tag_list])

df_small["Formatted_Tags"] = df_small["Top3_Predicted_Tags"].apply(format_tags)

df_small[["Ticket Description", "Formatted_Tags"]].head()

,Ticket Description,Formatted_Tags
0,I'm having an issue with the {product_purchase...,Technical Issue (0.88) | Complaint (0.87) | Bi...
1,I'm having an issue with the {product_purchase...,Complaint (0.93) | Technical Issue (0.86) | Pr...
2,I'm facing a problem with my {product_purchase...,Product Inquiry (0.88) | Complaint (0.87) | Te...
3,I'm having an issue with the {product_purchase...,Product Inquiry (0.55) | Complaint (0.42) | Te...
4,I'm having an issue with the {product_purchase...,Technical Issue (0.95) | Product Inquiry (0.95...

In [15]:
def few_shot_predict(text):
    prompt = f"""
You are a support ticket classifier.

Examples:

Ticket: I was charged twice for my order
Tags: Billing, Refund, Complaint

Ticket: I cannot log into my account
Tags: Account Access, Technical Issue

Ticket: My product has not been delivered
Tags: Shipping, Complaint

Now classify:

Ticket: {text}
Tags:
"""

    result = classifier(
        prompt,
        candidate_labels=labels,
        multi_label=True
    )

    return list(zip(result["labels"][:3], result["scores"][:3]))

In [16]:
few_results = []

for text in df_small["Ticket Description"]:
    res = few_shot_predict(text)
    few_results.append(res)

df_small["Few_Shot_Tags"] = few_results

In [17]:
df_small[[
    "Ticket Description",
    "Top3_Predicted_Tags",
    "Few_Shot_Tags"
]].head()

,Ticket Description,Top3_Predicted_Tags,Few_Shot_Tags
0,I'm having an issue with the {product_purchase...,"[(Technical Issue, 0.8753108978271484), (Compl...","[(Account Access, 0.8126041293144226), (Techni..."
1,I'm having an issue with the {product_purchase...,"[(Complaint, 0.9306432008743286), (Technical I...","[(Technical Issue, 0.9832305312156677), (Accou..."
2,I'm facing a problem with my {product_purchase...,"[(Product Inquiry, 0.8842090964317322), (Compl...","[(Technical Issue, 0.7701264023780823), (Shipp..."
3,I'm having an issue with the {product_purchase...,"[(Product Inquiry, 0.5504207611083984), (Compl...","[(Shipping, 0.777582585811615), (Technical Iss..."
4,I'm having an issue with the {product_purchase...,"[(Technical Issue, 0.9535007476806641), (Produ...","[(Technical Issue, 0.7426013350486755), (Compl..."

In [18]:
df_small.to_csv("final_support_ticket_results.csv", index=False)
print("FINAL FILE READY 🚀")

FINAL FILE READY 🚀